grails.plugin.repos.distribution.dgg="https://svn.codehaus.org/grails/trunk/grails-samples/dgg/plugins" 
grails.plugin.repos.discovery.dgg="http://svn.codehaus.org/grails/trunk/grails-samples/dgg/plugins" 
grails.project.work.dir = "target"
grails.project.test.reports.dir = "target/test-reports"
grails.project.plugins.dir = "plugins"
